/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as protectedLayoutRouteImport } from './pages/(protected)/_layout'
import { Route as OnboardingIndexRouteImport } from './pages/onboarding/index'
import { Route as protectedIndexRouteImport } from './pages/(protected)/index'
import { Route as AuthRegisterRouteImport } from './pages/auth/register'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as protectedGuestsRouteImport } from './pages/(protected)/guests'
import { Route as protectedCalendarRouteImport } from './pages/(protected)/calendar'
import { Route as protectedBookingsRouteImport } from './pages/(protected)/bookings'
import { Route as protectedStaffIndexRouteImport } from './pages/(protected)/staff/index'
import { Route as protectedPropertiesIndexRouteImport } from './pages/(protected)/properties/index'
import { Route as protectedStaffStaffIdRouteImport } from './pages/(protected)/staff/$staffId'
import { Route as protectedPropertiesPropertyIdRouteImport } from './pages/(protected)/properties/$propertyId'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedIndexRoute = protectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedGuestsRoute = protectedGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedCalendarRoute = protectedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedBookingsRoute = protectedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedStaffIndexRoute = protectedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedPropertiesIndexRoute =
  protectedPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedStaffStaffIdRoute = protectedStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedPropertiesPropertyIdRoute =
  protectedPropertiesPropertyIdRouteImport.update({
    id: '/properties/$propertyId',
    path: '/properties/$propertyId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/bookings': typeof protectedBookingsRoute
  '/calendar': typeof protectedCalendarRoute
  '/guests': typeof protectedGuestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof protectedIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/properties/$propertyId': typeof protectedPropertiesPropertyIdRoute
  '/staff/$staffId': typeof protectedStaffStaffIdRoute
  '/properties/': typeof protectedPropertiesIndexRoute
  '/staff/': typeof protectedStaffIndexRoute
}
export interface FileRoutesByTo {
  '/bookings': typeof protectedBookingsRoute
  '/calendar': typeof protectedCalendarRoute
  '/guests': typeof protectedGuestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof protectedIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/properties/$propertyId': typeof protectedPropertiesPropertyIdRoute
  '/staff/$staffId': typeof protectedStaffStaffIdRoute
  '/properties': typeof protectedPropertiesIndexRoute
  '/staff': typeof protectedStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(protected)/bookings': typeof protectedBookingsRoute
  '/(protected)/calendar': typeof protectedCalendarRoute
  '/(protected)/guests': typeof protectedGuestsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/(protected)/': typeof protectedIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/(protected)/properties/$propertyId': typeof protectedPropertiesPropertyIdRoute
  '/(protected)/staff/$staffId': typeof protectedStaffStaffIdRoute
  '/(protected)/properties/': typeof protectedPropertiesIndexRoute
  '/(protected)/staff/': typeof protectedStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/bookings'
    | '/calendar'
    | '/guests'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/onboarding/'
    | '/properties/$propertyId'
    | '/staff/$staffId'
    | '/properties/'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bookings'
    | '/calendar'
    | '/guests'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/onboarding'
    | '/properties/$propertyId'
    | '/staff/$staffId'
    | '/properties'
    | '/staff'
  id:
    | '__root__'
    | '/(protected)'
    | '/(protected)/bookings'
    | '/(protected)/calendar'
    | '/(protected)/guests'
    | '/auth/login'
    | '/auth/register'
    | '/(protected)/'
    | '/onboarding/'
    | '/(protected)/properties/$propertyId'
    | '/(protected)/staff/$staffId'
    | '/(protected)/properties/'
    | '/(protected)/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/guests': {
      id: '/(protected)/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof protectedGuestsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/calendar': {
      id: '/(protected)/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof protectedCalendarRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/bookings': {
      id: '/(protected)/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof protectedBookingsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/staff/': {
      id: '/(protected)/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof protectedStaffIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/properties/': {
      id: '/(protected)/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof protectedPropertiesIndexRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/staff/$staffId': {
      id: '/(protected)/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof protectedStaffStaffIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/properties/$propertyId': {
      id: '/(protected)/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof protectedPropertiesPropertyIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedBookingsRoute: typeof protectedBookingsRoute
  protectedCalendarRoute: typeof protectedCalendarRoute
  protectedGuestsRoute: typeof protectedGuestsRoute
  protectedIndexRoute: typeof protectedIndexRoute
  protectedPropertiesPropertyIdRoute: typeof protectedPropertiesPropertyIdRoute
  protectedStaffStaffIdRoute: typeof protectedStaffStaffIdRoute
  protectedPropertiesIndexRoute: typeof protectedPropertiesIndexRoute
  protectedStaffIndexRoute: typeof protectedStaffIndexRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedBookingsRoute: protectedBookingsRoute,
  protectedCalendarRoute: protectedCalendarRoute,
  protectedGuestsRoute: protectedGuestsRoute,
  protectedIndexRoute: protectedIndexRoute,
  protectedPropertiesPropertyIdRoute: protectedPropertiesPropertyIdRoute,
  protectedStaffStaffIdRoute: protectedStaffStaffIdRoute,
  protectedPropertiesIndexRoute: protectedPropertiesIndexRoute,
  protectedStaffIndexRoute: protectedStaffIndexRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
